// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import archival "github.com/uber/cadence/common/archival"
import mock "github.com/stretchr/testify/mock"

// Initiator is an autogenerated mock type for the Initiator type
type Initiator struct {
	mock.Mock
}

// Archive provides a mock function with given fields: request
func (_m *Initiator) Archive(request *archival.PutWorkflowRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(*archival.PutWorkflowRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
